-test5()
The error message you're encountering (TypeError: Help.close_help() missing 1 required positional argument: 'partner') indicates that the close_help method in your Help class requires an argument partner, but it is not receiving it when called.