-test2(read files content)
AttributeError: 'Convertor' object has no attribute 'file_contents'
this may be because of what type of file it is trying to read