V3-CanvasTable-test1()  <<<(!)>>>
-<<<After revaluation I decided to take things one step at a time we will start by inputting data and once we have that figure out we will switch to calculating that data diary out of files in folder, then we will learn how to input matching files in all file types into text box,  after that it's saving data results 2 folder as a file, and there's a bonus in text box will have an entry box to search up file names and a link to every file name and text box to open up a window displaying data.>>>
error: -I built this starter version in my row and it seems I forgot to add self. to some values.