-test2()
change:
add: self.column_widths = [60,100, 60]
          self.headers = ['place','Associate', 'total Points']
Error: Com's of information are out of place by 1
-i only add place to the heading of the table I also need to add place date to the tables results as well