ResultsExport window-test1()
due to how long this is taking i am forced to move on to the research window
error: i forgot to put in "if __name__ == "__main__":
  root = Tk()
  app = MainWindow(root)
  root.mainloop()"